### ISSUE TITLE
Nothing is working- globo.com

### ISSUE THREAD

**Issue by cavalcantero** [vitorhirota/repository.brazilian.xbmc-addons#4]
Hi, ever since the release on 7/2/15, the live channels and on demand links are not working.  It was working fine just then.  I'm a subscriber of globo.com and I'm using amazon fire tv.  I can stream just fine online on globo.com with my account.  It just says "one or more items failed to play.  Check the logs for details."  I'm running helix.
I'm fairly new to do this and I'm not sure how to get to the logs.  
Many thanks!!
:)

**Comment by rokam** [comment]
Check https://bitbucket.org/vitorhirota/repository.brazilian.xbmc-addons
Issue fixed
