### ISSUE TITLE
Include channel

### ISSUE THREAD

**Issue by fernandobayit** [vitorhirota/repository.brazilian.xbmc-addons#6]
Hello, I would like to know if there is a possibility to include other channels in the plugin, such as ESPN, EI, EI MAXX, EI MAXX2, Fox Sports, HBO. Because the user and password are the same which would make it much easier for those who have a password. Channel lists live offline.

**Comment by vitorhirota** [comment]
Hi @fernandogobah, please use the repo at https://bitbucket.org/vitorhirota/repository.brazilian.xbmc-addons/ to open up issues, since here is just a mirror. Thanks!
